import re
from typing import Annotated

from pydantic import AnyHttpUrl, BaseModel, Field, field_validator


class MedicalResponse(BaseModel):
    """Validated, source-grounded response generated by the chat model."""

    answer: Annotated[str, Field(min_length=1)]
    sources: Annotated[list[AnyHttpUrl], Field(min_length=1)]
    medical_warnings: list[str] = Field(default_factory=list)
    red_flags: list[str] = Field(default_factory=list)
    recommended_next_step: Annotated[str, Field(min_length=1)]
    confidence: Annotated[float, Field(ge=0, le=1)]

    @field_validator("sources")
    @classmethod
    def sources_must_use_https(cls, sources: list[AnyHttpUrl]) -> list[AnyHttpUrl]:
        if any(source.scheme != "https" for source in sources):
            raise ValueError("Semua sumber harus menggunakan HTTPS")
        return sources

    @field_validator("answer")
    @classmethod
    def answer_must_not_diagnose_or_prescribe(cls, answer: str) -> str:
        answer = answer.strip()
        if not answer:
            raise ValueError("Jawaban tidak boleh kosong")
        unsafe_patterns = (
            r"\b(?:anda|kamu|you)\s+(?:menderita|mengidap|terkena|pasti\s+mengalami|have|has)\b",
            r"\b(?:diagnosis|diagnose)\s+(?:anda|kamu|you)\s+(?:adalah|is)\b",
            r"\b(?:minum|konsumsi|gunakan|take|use)\b.{0,50}\b\d+\s*(?:mg|ml|tablet|kapsul)\b",
            r"\b(?:hentikan|berhenti|stop|discontinue)\b.{0,40}\b(?:obat|medication|medicine)\b",
        )
        if any(re.search(pattern, answer, re.IGNORECASE) for pattern in unsafe_patterns):
            raise ValueError("Jawaban tidak boleh memberikan diagnosis atau resep personal")
        return answer

    @field_validator("medical_warnings", "red_flags", mode="before")
    @classmethod
    def normalize_notice_lists(cls, value: list[str] | None) -> list[str]:
        if value is None:
            return []
        return [item.strip() for item in value if item and item.strip()]

    def to_text(self) -> str:
        """Render the validated result without changing the existing API contract."""
        sections = [self.answer]
        if self.medical_warnings:
            sections.append(
                "Peringatan medis:\n"
                + "\n".join(f"- {warning}" for warning in self.medical_warnings)
            )
        if self.red_flags:
            sections.append(
                "Tanda bahaya:\n"
                + "\n".join(f"- {red_flag}" for red_flag in self.red_flags)
            )
        sections.append(f"Langkah berikutnya: {self.recommended_next_step}")
        sections.append("Sumber:\n" + "\n".join(f"- {source}" for source in self.sources))
        return "\n\n".join(sections)
