"""revision table

Revision ID: 83a868b81826
Revises: aa993171a766
Create Date: 2026-03-02 21:44:41.241745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a868b81826'
down_revision: Union[str, Sequence[str], None] = 'aa993171a766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_base', 'fingerprint')
    op.drop_column('knowledge_base', 'ip_address')
    op.add_column('user_usage', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('user_usage', sa.Column('fingerprint', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_usage', 'fingerprint')
    op.drop_column('user_usage', 'ip_address')
    op.add_column('knowledge_base', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('knowledge_base', sa.Column('fingerprint', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
