"""revision table

Revision ID: 8ecc3e3233f7
Revises: 83a868b81826
Create Date: 2026-03-02 21:47:22.986584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecc3e3233f7'
down_revision: Union[str, Sequence[str], None] = '83a868b81826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_usage', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_usage', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
